### PR TITLE
pretend to resolve conflict

### PR DESCRIPTION
**Pull request by Criinal**

### CODE REVIEW

**Comment by satouriko** [comment]
pre…tend?

**Comment by Criinal** [comment]
emmmmm i knew once other's request had been accepted i would get "Please resolve conflict"...so i added "pretend"...just a kidding...i will pull a request soon

**Comment by Criinal** [comment]
emmmmm i knew once other's request had been accepted i would get "Please resolve conflict"...so i added "pretend"...just a kidding...I had already resolved the conflict,I hope this time it could be accepted...

**Comment by Criinal** [comment]
I wonder if I need to squash commits...emmmm let me try

**Comment by satouriko** [comment]
in fact i made everyone receives a conflict for the first time they submit this task deliberately to make sure they know how to merge updates. i noticed that you deleted your repository, which is a quite strange and unnecessary behavior, thus i sent you a conflict again.

**Comment by Criinal** [comment]
I am sorry...I deleted it by mistake...

**Pull request merged**
